version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000
    logging:
      driver: syslog
      options:
        syslog-address: "http://logstash-piggyfinance.app.openshiftcognizant.com:5044"

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build: account-service
    ports:
      - 6000:6000
    logging:
      driver: syslog
      options:
        syslog-address: "http://logstash-piggyfinance.app.openshiftcognizant.com:5044"  

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000
    logging:
      driver: syslog
      options:
        syslog-address: "http://logstash-piggyfinance.app.openshiftcognizant.com:5044"  

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  notification-service:
    build: notification-service
    ports:
      - 8000:8000
    logging:
      driver: syslog
      options:
        syslog-address: "http://logstash-piggyfinance.app.openshiftcognizant.com:5044"  

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  monitoring:
    build: monitoring
    logging:
      driver: syslog
      options:
        syslog-address: "http://logstash-piggyfinance.app.openshiftcognizant.com:5044"

  turbine-stream-service:
    build: turbine-stream-service
    logging:
      driver: syslog
      options:
        syslog-address: "http://logstash-piggyfinance.app.openshiftcognizant.com:5044"