spring:
  data:
    mongodb:
      host: mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: auth
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
