security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: statistics
      port: 27017

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io
  
logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    com.piggymetrics.statistics: DEBUG
  file: /var/lib/docker/containers/statistics-service/statistics-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
